/**
 * CrisisOS Vision AI Types
 * Strictly decoupled from deterministic risk calculation.
 * Gemini Vision is strictly for observational evidence, hazard detection, and grounded reasoning.
 */

export type VisionDisasterType =
  | 'flood'
  | 'fire'
  | 'landslide'
  | 'structural_damage'
  | 'road_blockage'
  | 'storm'
  | 'other'
  | 'uncertain';

export type VisionSeverityObservation =
  | 'low'
  | 'moderate'
  | 'high'
  | 'critical'
  | 'uncertain';

export type RoadAccessibility =
  | 'clear'
  | 'partially_blocked'
  | 'blocked'
  | 'unknown';

export type MedicalConcern =
  | 'none'
  | 'possible'
  | 'significant'
  | 'unknown';

/**
 * Structured output generated by Gemini Vision.
 * Must NOT contain numeric risk_score or priority_rank.
 */
export interface GeminiVisionAnalysis {
  summary: string;
  disaster_type: VisionDisasterType;
  severity_observation: VisionSeverityObservation;
  visible_hazards: string[];
  infrastructure_damage: string[];
  road_accessibility: RoadAccessibility;
  water_or_flooding_observed: boolean;
  people_visible: boolean;
  estimated_people_visible: number | null;
  medical_concern_observed: MedicalConcern;
  rescue_relevant_evidence: string[];
  confidence: number; // 0.0 to 1.0
  limitations: string[];
}

/**
 * Contextual grounding facts pulled from Supabase PostgreSQL.
 * Strictly deterministic and unmodifiable by Gemini.
 */
export interface VisionGroundingContext {
  zone_id?: string;
  zone_code: string;
  zone_name: string;
  sector: string;
  population: number;
  affected_population: number;
  risk_score: number; // Deterministic calculation only
  priority_rank: number; // Deterministic calculation only
  severity_label: string;
  source: 'supabase' | 'fallback';
}

/**
 * API Response from /api/vision
 */
export interface VisionApiResponse {
  status: 'ok' | 'error';
  code?: string;
  message?: string;
  model?: string;
  analysis?: GeminiVisionAnalysis;
  grounding?: VisionGroundingContext;
  source?: 'supabase' | 'server-cache';
  persistence?: {
    persisted: boolean;
    source: 'supabase' | 'server-cache';
    isTemporaryFallback?: boolean;
    imageId?: string;
    analysisId?: string;
    error?: string | null;
  };
  latencyMs?: number;
  timestamp?: string;
  transient?: boolean;
  attempts?: number;
}
